apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sno-1-oauth
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    helm:
      valueFiles:
        - values-oauth.yaml
    path: .
    repoURL: 'https://github.com/romerobu/helm-infra-gitops-workshop.git'
    targetRevision: ninja-talk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true